{   (None, 0, 'inductor_standalone'): (   'artifact_shape_None_subgraph_0',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_0'),
    (None, 1, 'inductor_standalone'): (   'artifact_shape_None_subgraph_1',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_1'),
    (None, 2, 'inductor_standalone'): (   'artifact_shape_None_subgraph_2',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_2'),
    (None, 3, 'inductor_standalone'): (   'artifact_shape_None_subgraph_3',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_3'),
    (None, 4, 'inductor_standalone'): (   'artifact_shape_None_subgraph_4',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_4'),
    (None, 5, 'inductor_standalone'): (   'artifact_shape_None_subgraph_5',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_5'),
    (None, 6, 'inductor_standalone'): (   'artifact_shape_None_subgraph_6',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_6'),
    (None, 7, 'inductor_standalone'): (   'artifact_shape_None_subgraph_7',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_7'),
    (None, 8, 'inductor_standalone'): (   'artifact_shape_None_subgraph_8',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_8'),
    (None, 9, 'inductor_standalone'): (   'artifact_shape_None_subgraph_9',
                                          '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_9'),
    (None, 10, 'inductor_standalone'): (   'artifact_shape_None_subgraph_10',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_10'),
    (None, 11, 'inductor_standalone'): (   'artifact_shape_None_subgraph_11',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_11'),
    (None, 12, 'inductor_standalone'): (   'artifact_shape_None_subgraph_12',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_12'),
    (None, 13, 'inductor_standalone'): (   'artifact_shape_None_subgraph_13',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_13'),
    (None, 14, 'inductor_standalone'): (   'artifact_shape_None_subgraph_14',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_14'),
    (None, 15, 'inductor_standalone'): (   'artifact_shape_None_subgraph_15',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_15'),
    (None, 16, 'inductor_standalone'): (   'artifact_shape_None_subgraph_16',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_16'),
    (None, 17, 'inductor_standalone'): (   'artifact_shape_None_subgraph_17',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_17'),
    (None, 18, 'inductor_standalone'): (   'artifact_shape_None_subgraph_18',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_18'),
    (None, 19, 'inductor_standalone'): (   'artifact_shape_None_subgraph_19',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_19'),
    (None, 20, 'inductor_standalone'): (   'artifact_shape_None_subgraph_20',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_20'),
    (None, 21, 'inductor_standalone'): (   'artifact_shape_None_subgraph_21',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_21'),
    (None, 22, 'inductor_standalone'): (   'artifact_shape_None_subgraph_22',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_22'),
    (None, 23, 'inductor_standalone'): (   'artifact_shape_None_subgraph_23',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_23'),
    (None, 24, 'inductor_standalone'): (   'artifact_shape_None_subgraph_24',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_24'),
    (None, 25, 'inductor_standalone'): (   'artifact_shape_None_subgraph_25',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_25'),
    (None, 26, 'inductor_standalone'): (   'artifact_shape_None_subgraph_26',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_26'),
    (None, 27, 'inductor_standalone'): (   'artifact_shape_None_subgraph_27',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_27'),
    (None, 28, 'inductor_standalone'): (   'artifact_shape_None_subgraph_28',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_28'),
    (None, 29, 'inductor_standalone'): (   'artifact_shape_None_subgraph_29',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_29'),
    (None, 30, 'inductor_standalone'): (   'artifact_shape_None_subgraph_30',
                                           '.vllm_cache/torch_compile_cache/3480888335/rank_0_0/backbone/artifact_shape_None_subgraph_30')}